# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-21 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_token', '0009_requesttokenerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text=b'Intended recipient of the JWT (can be used by anyone if not set).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
