# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("request_token", "0010_auto_20170521_1944")]

    operations = [
        migrations.AlterModelOptions(
            name="requesttoken",
            options={"verbose_name": "Token", "verbose_name_plural": "Tokens"},
        ),
        migrations.AlterModelOptions(
            name="requesttokenerrorlog",
            options={"verbose_name": "Error", "verbose_name_plural": "Errors"},
        ),
        migrations.AlterModelOptions(
            name="requesttokenlog",
            options={"verbose_name": "Log", "verbose_name_plural": "Logs"},
        ),
    ]
