# Generated by Django 3.1.7 on 2021-03-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_token", "0011_update_model_meta_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestTokenErrorLog",
        ),
    ]
