# Generated by Django 2.0.5 on 2018-05-23 05:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('request_token', '0011_update_model_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoken',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='Custom data add to the token, but not encoded (must be fetched from DB).', null=True),
        ),
    ]
