# Generated by Django 3.1.4 on 2020-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_token", "0011_update_model_meta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttoken",
            name="ttl",
            field=models.IntegerField(
                default=1,
                help_text="The number of requests before token is ejected from session (requires SessionTokenMiddleware).",
            ),
        ),
    ]
