# Generated by Django 3.1.4 on 2020-12-19 11:21

from django.conf import settings
from django.db import migrations, models

from ..models import RequestToken


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("request_token", "0011_update_model_meta_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesttoken",
            name="login_mode",
            field=models.CharField(
                choices=RequestToken.LoginMode.choices,
                default="NONE",
                help_text="How should the request be authenticated?",
                max_length=10,
            ),
        ),
    ]
