# Generated by Django 3.2.7 on 2023-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_token", "0012_delete_requesttokenerrorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttoken",
            name="token",
            field=models.TextField(
                default="", help_text="The encoded JWT token, set on save."
            ),
        ),
    ]
