# Generated by Django 3.1.4 on 2020-12-19 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("request_token", "0013_convert_login_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttoken",
            name="stash",
            field=models.BooleanField(
                default=True, help_text="Add token object to user session if True."
            ),
        ),
        migrations.AlterField(
            model_name="requesttoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Intended recipient of the JWT (can be used by anyone if not set).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requesttokenlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who made the request (None if anonymous).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
